wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705374521.738222
    t:
      1:
      - 1
      - 37
      - 41
      - 55
      - 60
      - 63
      3:
      - 13
      - 23
      4: 3.8.10
      5: 0.16.2
      8:
      - 5
      - 9
      13: linux-x86_64
